# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andyteki
email: andy02081224@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chen Yu的個人網站
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.andyteki.com" # the base hostname & protocol for your site
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

markdown_ext:  markdown,mkdown,mkdn,mkd,md

# Prose settings
prose:
  siteurl: 'https://www.andyteki.com'
  media: 'img'
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /css
    - /js
    - .gitignore
    - _config.yml
    - index.html
    - CNAME 
    - apple-touch-icon.png
    - bs-config.js
    - favicon-32x32.png
    - favicon-96x96.png
    - favicon.ico
    - feed.xml
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "標題*"
          type: text
      - name: "subtitle"
        field:
          element: "text"
          label: "副標題"
          type: text
      - name: cover_image
        field:
          element: "text"
          label: "封面圖片(路徑)"
          type: text
      - name: category
        field:
          element: select
          label: "分類"
          options: 
            - "技術"
            - "murmur"
      - name: published
        field:
          element: checkbox
          label: "發布"
          value: true
      - name: tags
        field:
          element: multiselect
          label: "標籤"
          options:
            - "HTML"
            - "CSS"
            - "JavaScript"
            # - "工具"
            # - "Node"
            # - "React"
            # - "語言"
            # - "資料庫"
            # - "Jekyll"
            # - "職涯"
            # - "設計"
            
# Custom data
codepen_username: andy02081224
github_username:  andy02081224
homepage_title: Chen Yu
homepage_subtitle: 哈囉，我來自地球。
