# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andyteki
email: andy02081224@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chen Yu的個人網站
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.andyteki.com" # the base hostname & protocol for your site
codepen_username: andy02081224
github_username:  andy02081224
homepage_title: Chen Yu
homepage_subtitle: Just wanna write something here

# Build settings
markdown: kramdown
kramdown:
  input: GFM

markdown_ext:  markdown,mkdown,mkdn,mkd,md